version: '3.8'

services:
  data_ingestion:
    build:
      context: .
      dockerfile: data_ingestion/Dockerfile
    volumes:
      - ./dat:/app/dat         # Mount your local 'data' directory for downloaded files
      - ./logs:/app/logs         # Mount your local 'data' directory for downloaded files
    environment:
      - TZ=America/Vancouver      # Set the timezone to 
    restart: always               # Restart the container if it stops
