# Use a lightweight base image compatible with Raspberry Pi (ARM-based architecture)
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy your requirements file to install dependencies
COPY requirements-rpi.txt .

# Install necessary Python libraries for the script
RUN pip install --no-cache-dir -r requirements-rpi.txt

# Copy the main script to the container
COPY . .

# Run the script indefinitely
CMD ["python", "-u", "src/data_injestion.py"]
